language: python
python:
  - "3.5"
dist: trusty
sudo: false

services:
  - postgresql

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libpq-dev

install:
  #- python3 ./install.py --test --no-db
  - pip3 install -r requirements.txt -r requirements.postgres.txt -r requirements.dev.txt --upgrade
  - npm install
  - npm run build

before_script:
  - psql -c 'CREATE DATABASE jarr_test;' -U postgres
  - echo '{"jarr_testing":true,"crawler":{"login":"admin","passwd":"admin"},"log":{"level":10},"sqlalchemy":{"test_uri":"postgres:///jarr_test","db_uri":"postgres:///jarr_test"}}' > ~/.config/jarr.json

script:
  - JARR_TESTING=true nosetests -v --with-coverage --cover-package=jarr,jarr_common,jarr_crawler
  # ignoring aligning / line breaking non-sens
  - pep8 --ignore=E126,E127,E128,W503 jarr/ --exclude=jarr/migrations,__pycache__
  - pep8 --ignore=E126,E127,E128,W503 jarr_crawler/ --exclude=__pycache__
  - pep8 --ignore=E126,E127,E128,W503 jarr_common/ --exclude=__pycache__

after_success:
  - coveralls
